### ISSUE TITLE
The commands: 8D & bassboost

### ISSUE THREAD

**Issue by dxrk09** [Whirl21/Musico#17]
![Capture](https://user-images.githubusercontent.com/118543407/203554376-e3443f5c-36d5-4f11-aea1-6988cd8caec6.PNG)
How can i solve this error ?

**Comment by whirlxd** [comment]
since i dont maintain this repo really anymore 
1) either debug it and fix it yourself [ refer to the music module's docs ] 
 2) remove the command 
your wish witherway

**Comment by whirlxd** [comment]
if you do manage to fix it , feel free to open a pull request and helping others like you

**Comment by vitaminion0001** [comment]
the commands are missing a syntax
this:

`		if (
			interaction.guild.me.voice.channel &&
			interaction.member.voice.channel.id !==
				interaction.guild.me.voice.channel.id
		)`

should be this:

`		if (
			interaction.guild.members.me.voice.channel &&
			interaction.member.voice.channel.id !==
				interaction.guild.members.me.voice.channel.id
		)`

change that in the non working commands and they start working again.

sadly not in the position to open a pull so leaving it here as fix.

**Comment by whirlxd** [comment]
aight
