### ISSUE TITLE
[HELP] Bot Didn't Respond To Any Command 

### ISSUE THREAD

**Issue by overfy** [Whirl21/Musico#3]
![Screenshot_192](https://user-images.githubusercontent.com/95896781/148023408-f759fd00-d726-4203-831d-a2f2759c4539.png)
![Screenshot_193](https://user-images.githubusercontent.com/95896781/148023529-20e9849d-afae-4768-83fb-8aa3050d4063.png)
`
When i am trying to run any command like /help /play, bot didn't respond
`

**Comment by Whirl21** [comment]
you need node v16+
replit only supports v12

**Comment by overfy** [comment]
> you need node v16+ replit only supports v12

i already update it to node 16+ using this method https://dev.to/arnavkr/updating-node-js-to-16-in-replit-1ep0
but the command still didn't work sir :(,

**Comment by Whirl21** [comment]
well then have you given it the required scopes and permissions?

**Comment by overfy** [comment]
> well then have you given it the required scopes and permissions?

i already giving the permission and scopes, and i think if the nodes goes back to v12 its will show "unexpected token ? " :( ( because the first time i run the bot before i upgrade to v16 its shows that " unexpected token ? error " ), i think i will try to run it on my local computers. sorry for my bad english & thankyou

**Comment by overfy** [comment]
![Screenshot_199](https://user-images.githubusercontent.com/95896781/148562592-07a6ebc8-d166-4d47-8117-d4e86d9f9746.png)
already tested on my local pc using node v16.13.1 & giving all presence & administrator permission, but bot still didn't respond to any command  :(

**Comment by overfy** [comment]
![Screenshot_200](https://user-images.githubusercontent.com/95896781/148563248-ffd2886c-e086-47f7-a673-2ca00ed3be75.png)
the slash command also doesn't appear here.

**Comment by Whirl21** [comment]
can re-add your bot and give it the permission of admin this time and a admin role aswell
if the issue still exists then drop me a dm on discord - Whirl#0007

**Comment by overfy** [comment]
> can re-add your bot and give it the permission of admin this time and a admin role aswell if the issue still exists then drop me a dm on discord - Whirl#7

i already re-add the bot, giving administrator permission & giving administrator role, but still nothing happend :(

**Comment by overfy** [comment]
![Screenshot_207](https://user-images.githubusercontent.com/95896781/148670361-10f340d9-7f16-45c9-955a-eec76811c3f9.png)
already added you in discord too :D, my username is bims#1

**Comment by overfy** [comment]
thankyou @Whirl21
