### ISSUE TITLE
Problems With playlistPlayback

### ISSUE THREAD

**Issue by virtualized-human** [Whirl21/Musico#4]
Hello,

i already asked in twitter (hopfully ill get an answer) for you discord tag. Or add me: dotxyz#2418!

I saw a bug and i tried to fix but idk how. Something is wrong with the /home/discord/Musico/commands/slash/music/play.js

See the Video for Issue:

https://cloud.dotxyz.cf/index.php/s/gcCMLpbBGaitP3t

i hope you undestand this...

I think the playlist need to be buggfixxed.

I wish me a anticrash also, is some error comes so the bot wont crash if something went wrong!

**Comment by virtualized-human** [comment]
Ill saw you tag and added you :)

**Comment by whirlxd** [comment]
could you send the video file as mp4 here.
since i don't want to open that link :(

**Comment by virtualized-human** [comment]
i cant upload...

**Comment by virtualized-human** [comment]
AH i can. wait a minet

**Comment by virtualized-human** [comment]
https://user-images.githubusercontent.com/92203938/151698351-3e1bdef8-d46c-41bf-942c-a9e9f733c742.mp4

**Comment by virtualized-human** [comment]
Also... Can we chat in Discord over that, i think that may bee better?

**Comment by virtualized-human** [comment]
and?

**Comment by whirlxd** [comment]
mhm 
i see
i don't know if this is an error on the code part or the package.
could you just debug it (play.js file)

**Comment by whirlxd** [comment]
also i accidently ignored your request before i saw this issue and thought it was a random person so please send it again

**Comment by virtualized-human** [comment]
You mean, that i show the terminal while doing?

**Comment by virtualized-human** [comment]
or npm run dev?

**Comment by virtualized-human** [comment]
Now i reinstalled the bot, so i can test better because i got issues (of changing a bit something in code like added  a clear filer button that worked) and now im getting this error on /play with vailid link:


`[ERROR]
DiscordAPIError: Unknown interaction
/home/discord/wave/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:138
    if (!this.deferred && !this.replied) throw new Error('INTERACTION_NOT_REPLIED');
                                               ^

Error [INTERACTION_NOT_REPLIED]: The reply to this interaction has not been sent or deferred.
    at CommandInteraction.editReply (/home/discord/wave/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:138:48)
    at Object.execute (/home/discord/wave/events/slashCreate.js:40:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.<anonymous> (/home/discord/wave/handlers/eventsHandler.js:18:24) {
  [Symbol(code)]: 'INTERACTION_NOT_REPLIED'
}`

Used commands to install:

wget https://github.com/Whirl21/Musico/archive/refs/tags/v3.5.zip
unzip v3.5.zip 
mv Musico-3.5/ wave
cd wave/
ls
nano musico.config.js (added vailid token and ids)
npm i
node musico.js 

(also seeable in video that i compressed so its not so seeable but yes)
what do i need to do to fix it?

https://user-images.githubusercontent.com/92203938/152113076-526e9bcc-b6bb-42ca-b337-ca8dc52dda64.mp4

**Comment by virtualized-human** [comment]
and the login things that i leaked not working so you dont need to say me xD

**Comment by whirlxd** [comment]
actually you are installing an older version
i haven't pushed the new one to releases yet.
Just clone the repo now , i deleted the previous release

**Comment by virtualized-human** [comment]
i tried it bevore with clone...

but here:

LOG

root@146:/home/discord/wave# node musico.js 

  ███╗   ███╗██╗   ██╗███████╗██╗ ██████╗ ██████╗                               
  ████╗ ████║██║   ██║██╔════╝██║██╔════╝██╔═══██╗                              
  ██╔████╔██║██║   ██║███████╗██║██║     ██║   ██║                              
  ██║╚██╔╝██║██║   ██║╚════██║██║██║     ██║   ██║                              
  ██║ ╚═╝ ██║╚██████╔╝███████║██║╚██████╗╚██████╔╝                              
  ╚═╝     ╚═╝ ╚═════╝ ╚══════╝╚═╝ ╚═════╝ ╚═════╝                               
                                                                                
                      ██████╗ ██╗   ██╗    ██╗    ██╗██╗  ██╗██╗██████╗ ██╗     
                      ██╔══██╗╚██╗ ██╔╝    ██║    ██║██║  ██║██║██╔══██╗██║     
                      ██████╔╝ ╚████╔╝     ██║ █╗ ██║███████║██║██████╔╝██║     
                      ██╔══██╗  ╚██╔╝      ██║███╗██║██╔══██║██║██╔══██╗██║     
                      ██████╔╝   ██║       ╚███╔███╔╝██║  ██║██║██║  ██║███████╗
                      ╚═════╝    ╚═╝        ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚══════╝
                                                                                
  
[Musico] | Logged in as Wave#6839!
[Musico] | Servers! ["9"]
[Musico] | Users! ["2"]
[Musico] | Channels! ["243"]
[Musico] | Loaded all (/) commands
WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
MinigetError: Status code: 410
    at ClientRequest.<anonymous> (/home/discord/wave/node_modules/miniget/dist/index.js:210:27)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10) {
  statusCode: 410
}
PlayerError: [PlayerError] Cannot play a resource that has already ended.
    at new PlayerError (/home/discord/wave/node_modules/discord-player/dist/Structures/PlayerError.js:28:15)
    at StreamDispatcher.<anonymous> (/home/discord/wave/node_modules/discord-player/dist/VoiceInterface/StreamDispatcher.js:169:48)
    at Generator.next (<anonymous>)
    at /home/discord/wave/node_modules/discord-player/dist/VoiceInterface/StreamDispatcher.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/discord/wave/node_modules/discord-player/dist/VoiceInterface/StreamDispatcher.js:4:12)
    at StreamDispatcher.playStream (/home/discord/wave/node_modules/discord-player/dist/VoiceInterface/StreamDispatcher.js:165:16)
    at Timeout._onTimeout (/home/discord/wave/node_modules/discord-player/dist/Structures/Queue.js:675:33)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  createdAt: 2022-02-02T07:55:12.753Z,
  statusCode: 'PlayerError'
}

These errors comes after use /play valid link...

can we also chat over discord or is this a problem? dotxyz#2418
![image](https://user-images.githubusercontent.com/92203938/152114986-7e60e930-1dff-4de4-9ef7-f431797871cb.png)

VIDEO:

https://user-images.githubusercontent.com/92203938/152115185-f41bc7f4-df5e-4a47-8ebe-fb594dd2a2fd.mp4

**Comment by virtualized-human** [comment]
i updated npm install ytdl-core@latest as it sayed works now wih youtube and spotify

**Comment by virtualized-human** [comment]
but playlist still dont work... only if i play a single song, and skip to playlist...

**Comment by virtualized-human** [comment]
without errror idk

**Comment by virtualized-human** [comment]
https://user-images.githubusercontent.com/92203938/152116877-fcad5921-8daf-4002-b759-b2c4d4ad50ee.mp4


Please also add a anticrash for any error with permissions because the bot crashs, if the bot dont have enought permissions on a user that can be appused... Also a filter clear command and button. Thats what i think will make the bot better. than you need to fix the playlist system if it is not a package issue...

**Comment by whirlxd** [comment]
i ignored your friend request, send it again

**Comment by virtualized-human** [comment]
sendet.

**Comment by virtualized-human** [comment]
![image](https://user-images.githubusercontent.com/92203938/152353734-0a13e62c-4144-4cdd-aa71-4775965693a3.png)

**Comment by virtualized-human** [comment]
im now online.

**Comment by virtualized-human** [comment]
i also get no view information (only on every song the number 0) on spotify songs. i think that need to be fixxed or disabled also...

**Comment by whirlxd** [comment]
hm
ig it's a problem  with the package
ask in their support server

**Comment by virtualized-human** [comment]
What package?

**Comment by whirlxd** [comment]
discord-player
https://discord-player.js.org :)
