### ISSUE TITLE
[FEATURE REQUEST] In depth tutorial for setting up.

### ISSUE THREAD

**Issue by IntoTheVoid-900** [Whirl21/Musico#5]
Hey, this is an awesome project! I want to install it on my server, but the link on your website leads to an error, and I have no idea how to self-host it. Could you insert an in-depth tutorial on how to set it up? Please assume it is for a complete beginner who has no idea what they're doing.

**Comment by Whirl21** [comment]
Hy there thanks for your feedback i'll be sure to add an in-depth tutorial in guides folder or my blog 
Btw can you give me the link which leads to an error?

**Comment by IntoTheVoid-900** [comment]
On your website, it says "Completely free of cost , no premiuem bullshit click [Invite musico](https://discord.com/api/oauth2/authorize?client_id=876761541481992212&permissions=2184301889&redirect_uri=https%3A%2F%2Fmusico.whirl.codes&scope=bot%20applications.commands). When I click it asks me to log in to discord, and when I sign in it says "Invalid OAuth2 redirect_uri" (not a typo, it is how it is spelt).

**Comment by Whirl21** [comment]
I see
I'll update the invite link once I host the bot on cloud

**Comment by IntoTheVoid-900** [comment]
Okay, thanks

**Comment by IntoTheVoid-900** [comment]
Can you please tell me here when you have fixed those issues?

**Comment by Whirl21** [comment]
which issueS?
