### ISSUE TITLE
Ev cmnd not working

### ISSUE THREAD

**Issue by thejeshvarma** [Whirl21/Musico#7]
Hi whirl ! When I use this code to my bot eval cmd is not working ! In channel it's showing an error occured  : in console its showing (clean is not a function ) how to solve this ¿

**Comment by whirlxd** [comment]
clean is not a function?
ig that's reffering to the clean function.
since i don't have a lot of time to guide you throught this 
just paste this on top of the eval.js file 
```js
const clean = async (client, text) => {
	// If our input is a promise, await it before continuing
	if (text && text.constructor.name == "Promise") text = await text;

	if (typeof text !== "string")
		text = require("util").inspect(text, { depth: 1 });

	text = text
		.replace(/`/g, "`" + String.fromCharCode(8203))
		.replace(/@/g, "@" + String.fromCharCode(8203))
		.replaceAll(client.token, "T0$&N^");

	// Send off the cleaned up result
	return text;
};
```
this will work

**Comment by thejeshvarma** [comment]
Ok I will try , ty

**Comment by thejeshvarma** [comment]
Could you provide your server link? I m not able contact u coz that discord profile link is not opening.

**Comment by whirlxd** [comment]
uh sure 
https://discord.gg/zXbV7AR8TV
